server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # MIME correto para o manifest do PWA
    location = /manifest.webmanifest {
        default_type application/manifest+json;
    }
    # Service worker sempre fresco
    location = /sw.js {
        default_type application/javascript;
        add_header Cache-Control "no-cache";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
